backend:
  name: git-gateway
  branch: main

local_backend: true

locale: de

media_folder: static/img
public_folder: /img

collections:
  - name: "wichtig"
    label: "Datenschutz & CO."
    format: "frontmatter"
    extension: 'md'
    folder: "content/wichtig"
    create: true
    sortable_fields: ["title"]
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "seiten"
    label: "Seiten"
    format: "frontmatter"
    extension: 'md'
    folder: "content/seiten"
    create: true
    sortable_fields: ["title"]
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - label: "Landing"
        name: "landing"
        widget: "object"
        fields:
          - { label: "Landing Bild", name: "landingImage", widget: "image", required: false }
          - { label: "Landing Titel", name: "landingTitle", widget: "string", required: false }
          - { label: "Landing Subtitel", name: "landingSubtitle", widget: "markdown", required: false }
      - label: "Inhaltsblock"
        name: "content"
        widget: "list"
        fields:
          - { label: "Titel", name: "title", widget: "string", required: false }
          - { label: "Inhalt", name: "body", widget: "markdown", required: false }
          - { label: "Bild", name: "image", widget: "image", required: false }
          - { label: "Inhaltspositionierung", name: "position", widget: "select", options: ["links", "mitte", "rechts"], required: false }
          - { label: "Kleinerer Abstand nach oben?", name: "noPaddingTop", widget: "boolean", required: false, default: false }
          - { label: "Hervorgehoben ?", name: "highlight", widget: "boolean", required: false }
          - label: "Karten"
            name: "cards"
            widget: "list"
            fields:
              - { label: "Titel", name: "title", widget: "string", required: false }
              - { label: "Inhalt", name: "body", widget: "markdown", required: false }
              - { label: "Link", name: "link", widget: "string", required: false }
              - { label: "Linktext", name: "linktext", widget: "string", required: false }
              - { label: "Bild", name: "image", widget: "image", required: false }
          - label: "Banner"
            name: "banner"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Titel", name: "title", widget: "string", required: false} 
              - { label: "Inhalt", name: "body", widget: "markdown", required: false }
              - { label: "Link", name: "link", widget: "string", required: false }
              - { label: "Linktext", name: "linktext", widget: "string", required: false }
          - label: "Kundenmeinungen einbinden?"
            name: "kundenmeinungen"
            widget: "object"
            required: false
            collapsed: true
            fields:
              - { label: "Kategorie", name: "category", widget: "select", options: ["Generell", "Moderation", "Poetry Slam", "Kleinkunst", "Workshops", "Kabarett"], required: false }
              - { label: "Kundenmeinungen anzeigen ?", name: "show", widget: "boolean", required: false }
          - { label: "Termine einbinden?", name: "termine", widget: "boolean", required: false }
          - label: "Bild Gallerie"
            name: "gallery"
            widget: "list"
            required: false
            collapsed: true
            fields:
              - { label: "Bild", name: "image", widget: "image", required: false }
              - { label: "Bildunterschrift", name: "caption", widget: "string", required: false }
          - label: "Videos"
            name: "videos"
            widget: "list"
            required: false
            collapsed: true
            fields:
              - { label: "Video", name: "video", widget: "string", required: false }
              - { label: "Video Untertitel", name: "caption", widget: "string", required: false }
          - label: "Downloads"
            name: "downloads"
            widget: "list"
            required: false
            collapsed: true
            fields:
              - { label: "Datei", name: "file", widget: "file", multiple: true, required: false }
              - { label: "Datei Untertitel", name: "caption", widget: "string", required: false }
          - label: "Instagram"
            name: "instagram"
            widget: "boolean"
            required: false
            default: false